name: voxeldash
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  retry: ^3.1.2
  adaptive_theme: ^3.6.0
  google_fonts: ^6.2.1
  toastification: ^2.3.0
  connectivity_plus: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  introduction_screen: ^3.1.14
  lottie: ^3.1.3
  flutter_vector_icons: ^2.0.0
  day_night_switcher: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # Assets
  assets:

    # Animations
    - assets/anim/